### ISSUE TITLE
compilation fails on scalajs

### ISSUE THREAD

**Issue by antonkulaga** [cretz/scala-web-ideal#1]
:scala-web-ideal-client:compileScalaJs FAILED

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scala-web-ideal-client:compileScalaJs'.
> Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

**Comment by cretz** [comment]
Yes, this something that will be solved by https://github.com/scala-js/scala-js/issues/1685 but for now, download the standalone distribution at http://www.scala-js.org/downloads.html for the scala JS version in the https://github.com/cretz/scala-web-ideal/blob/master/build.gradle file and extract it adjacent to where this is checked out.

It is visible at https://github.com/cretz/scala-web-ideal/blob/master/client/build.gradle#L16 where I actually reference the manually-extracted Scala.js JARs. I'll leave this open until it's resolved with either me updating the Gradle file to download Scala.js or finding the CLI JARs on Maven.
